---
sudo: required
language: python
services: docker

python:
  - "2.7"
install:
  - pip install tox
script:
  - tox -v
  - gradle --no-daemon check
after_script:
  - cat build/reports/codenarc/main.txt

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
