---
sudo: required
language: python
services: docker

python:
  - "2.7"
before_install:
  - sudo apt-get install ca-certificates unzip openjdk-8-jdk wget
install:
  - pip install tox
script:
  - tox -v
