---
- name: Manage Agents
  jenkins_script:
    script: "{{ lookup('template', 'agent.groovy') }}"
    url: "{{ jenkins.host }}"
    user: "{{ jenkins.user }}"
    password: "{{ jenkins.password }}"
    validate_certs: no
  register: state_result
  changed_when: "'CHANGED' in state_result.output"

