---
- name: Manage Credentials
  jenkins_script:
    script: "{{ lookup('template', 'credential.groovy') }}"
    url: "{{ jenkins.host }}"
    user: "{{ jenkins.user }}"
    password: "{{ jenkins.password }}"
    validate_certs: no
  register: state_result
  with_dict: "{{ jenkins.credentials }}"
  changed_when: "'CHANGED' in state_result.output"
  failed_when: "'FAILED' in state_result.output"
