---
- name: Manage Credentials
  jenkins_script:
    script: "{{ lookup('template', 'credentials.groovy') }}"
    url: "{{ jenkins.host }}"
    user: "{{ jenkins.user }}"
    password: "{{ jenkins.password }}"
    timeout: 600
  register: creds_state_result
  changed_when: "'CHANGED' in creds_state_result.output"
