---
- name: Get system state old
  xml:
    path: "{{jenkins.mounted_homedir}}/config.xml"
    xpath: /hudson/installState/isSetupComplete
    content: text
  register: xmlresp_old
  ignore_errors: yes

- name: Get system state new
  xml:
    path: "{{jenkins.mounted_homedir}}/config.xml"
    xpath: /hudson/installStateName
    content: text
  register: xmlresp_new
  ignore_errors: yes

- name: Get initial password
  slurp:
    src: "{{jenkins.mounted_homedir}}/secrets/initialAdminPassword"
  register: initial_password_file

- name: Initial management user setup
  jenkins_script:
    script: "{{ lookup('template', 'management_user.groovy') }}"
    url: "{{ jenkins.host }}"
    user: admin
    password: '{{ initial_password_file["content"] | b64decode | trim }}'
    timeout: 600
  register: management_user_state_result
  changed_when: "'CHANGED' in management_user_state_result.output"
  when: (xmlresp_old.matches is defined and xmlresp_old.matches[0].isSetupComplete == "false") or
        (xmlresp_new.matches is defined and xmlresp_new.matches[0].installStateName == 'NEW')
