---
- import_tasks: wait.yml

- import_tasks: initial.yml
  when: jenkins.mounted_homedir is defined

- import_tasks: plugins.yml
  when: jenkins.plugin_manager is defined

- import_tasks: system.yml
  when: jenkins.system is defined

- import_tasks: users.yml
  when: jenkins.users is defined

- import_tasks: credentials.yml
  when: jenkins.credentials is defined

- import_tasks: agents.yml
  when: jenkins.agents is defined

