---
- import_tasks: wait.yml

- import_tasks: initial.yml
  when: jenkins.mounted_homedir is defined

- import_tasks: plugins.yml
  when: jenkins.plugin_manager is defined

- import_tasks: system.yml
  when: jenkins.system is defined

- import_tasks: security.yml
  when: jenkins.security is defined

- import_tasks: users.yml
  when: jenkins.users is defined

- import_tasks: credentials.yml
  when: jenkins.credentials is defined

- import_tasks: agents.yml
  when: jenkins.agents is defined

- import_tasks: mailer.yml
  when: jenkins.mailer is defined

- import_tasks: script_approval.yml
  when: jenkins.script_approval is defined

- import_tasks: matrix.yml
  when:
    - jenkins.security is defined
    - jenkins.security.auth_strategy is defined
    - jenkins.security.auth_strategy.permissions is defined
    - jenkins.security.auth_strategy.type == 'matrix' or jenkins.security.auth_strategy.type == 'project_matrix'

- import_tasks: ldap.yml
  when:
    - jenkins.security is defined
    - jenkins.security.access_control is defined
    - jenkins.security.access_control.realm is defined
    - jenkins.security.access_control.realm == 'ldap'

- import_tasks: theme.yml
  when:
    - jenkins.theme is defined

