---
- name: Manage Plugins
  jenkins_script:
    script: "{{ lookup('template', 'plugins.groovy') }}"
    url: "{{ jenkins.host }}"
    user: "{{ jenkins.user }}"
    password: "{{ jenkins.password }}"
    timeout: 600
  register: plugin_out
  changed_when: "'CHANGED' in plugin_out.output"

- name: Prepare instance for restart
  jenkins_script:
    script: "{{ lookup('template', 'restart.groovy') }}"
    url: "{{ jenkins.host }}"
    user: "{{ jenkins.user }}"
    password: "{{ jenkins.password }}"
    timeout: 3600
  register: ifrestart_out
  changed_when: "'CHANGED' in ifrestart_out.output"
  when: "'CHANGED' in plugin_out.output"

- name: Restart instance
  jenkins_script:
    script: "println 'CHANGED'; jenkins.model.Jenkins.instance.safeRestart()"
    url: "{{ jenkins.host }}"
    user: "{{ jenkins.user }}"
    password: "{{ jenkins.password }}"
  register: dorestart
  changed_when: "True"
  when:
    - "'CHANGED' in plugin_out.output"
    - "'CHANGED' in ifrestart_out.output"

- import_tasks: wait.yml
  when:
    - "'CHANGED' in plugin_out.output"
    - dorestart.changed

