---
- name: Manage In-process Script Approval
  jenkins_script:
    script: "{{ lookup('template', 'plugin.script_approval.groovy') }}"
    url: "{{ jenkins.host }}"
    user: "{{ jenkins.user }}"
    password: "{{ jenkins.password }}"
    timeout: 600
  register: script_approval_state_result
  changed_when: "'CHANGED' in script_approval_state_result.output"
