---
- name: Manage Users
  jenkins_script:
    script: "{{ lookup('template', 'users.groovy') }}"
    url: "{{ jenkins.host }}"
    user: "{{ jenkins.user }}"
    password: "{{ jenkins.password }}"
    timeout: 600
  register: users_state_result
  changed_when: "'CHANGED' in users_state_result.output"
